name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip openjdk-8-jdk unzip zip \
                                  build-essential libssl-dev libffi-dev \
                                  libsqlite3-dev liblzma-dev libjpeg-dev zlib1g-dev
          pip3 install --upgrade pip
          pip3 install cython==0.29.37 buildozer

      - name: Install Android SDK & NDK
        run: yes | buildozer android sdk

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ControlKivy-debug-apk
          path: bin/*.apk
