name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip openjdk-8-jdk unzip zip \
                                  build-essential libssl-dev libffi-dev \
                                  libsqlite3-dev liblzma-dev libjpeg-dev zlib1g-dev
          pip3 install --upgrade pip
          pip3 install cython==0.29.37 buildozer

      - name: Install Android SDK components & accept licenses
        run: |
          # Ruta donde Buildozer baja el SDK
          ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk

          # Instala commandlinetools si no existen
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          # (Buildozer ya debería haber descargado cmdline-tools, pero por si acaso)
          # wget -qO- https://dl.google.com/android/repository/commandlinetools-linux-9472_latest.zip \
          #   | bsdtar -xvf- -C $ANDROID_SDK_ROOT/cmdline-tools

          # Acepta todas las licencias
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses

          # Instala las plataformas y build-tools que necesita Kivy
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0"

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ControlKivy-debug-apk
          path: bin/*.apk
